# Generated by Django 3.2.4 on 2023-10-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumnos', models.IntegerField(db_column='idAlumno', primary_key=True, serialize=False)),
                ('nameAlumno', models.CharField(db_column='nameAlumno', max_length=100)),
            ],
            options={
                'db_table': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='RegistroU',
            fields=[
                ('id_registroU', models.IntegerField(db_column='idGenero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='tipoGenero', max_length=100)),
                ('apellidop', models.CharField(db_column='apellidoPaterno', max_length=100)),
                ('apellidom', models.CharField(db_column='apellidoMaterno', max_length=100)),
            ],
            options={
                'db_table': 'Genero',
            },
        ),
        migrations.CreateModel(
            name='Alumno_has_Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Alumno', models.ForeignKey(db_column='fk_Alumno', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('fk_Genero', models.ForeignKey(db_column='fk_Genero', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.registrou')),
            ],
            options={
                'db_table': 'Alumno_has_Genero',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='fk_genero',
            field=models.ForeignKey(db_column='fk_genero', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.registrou'),
        ),
    ]
