# Generated by Django 3.2.4 on 2023-10-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nameUsuario', models.CharField(db_column='nameUsusario', max_length=100)),
                ('fk_genero', models.ForeignKey(db_column='fk_genero', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.registrou')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario_has_Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Genero', models.ForeignKey(db_column='fk_Genero', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.registrou')),
                ('fk_Usuario', models.ForeignKey(db_column='fk_Usuario', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Usuario_has_Genero',
            },
        ),
        migrations.RemoveField(
            model_name='alumno_has_genero',
            name='fk_Alumno',
        ),
        migrations.RemoveField(
            model_name='alumno_has_genero',
            name='fk_Genero',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Alumno_has_Genero',
        ),
    ]
