# Generated by Django 3.2.4 on 2023-10-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231003_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idRegistro', models.IntegerField(db_column='idRegistro', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_column='usuario', max_length=100)),
                ('correo', models.EmailField(db_column='correo', max_length=254)),
                ('password', models.CharField(db_column='password', max_length=100)),
                ('password2', models.CharField(db_column='password2', max_length=100)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fk_genero',
        ),
        migrations.RemoveField(
            model_name='usuario_has_genero',
            name='fk_Genero',
        ),
        migrations.RemoveField(
            model_name='usuario_has_genero',
            name='fk_Usuario',
        ),
        migrations.DeleteModel(
            name='RegistroU',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Usuario_has_Genero',
        ),
    ]
