# Generated by Django 3.2.4 on 2023-10-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20231004_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='password2',
        ),
    ]
