# Generated by Django 3.2.4 on 2023-10-18 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20231018_1725'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='preguntas',
            table='Pregruntas',
        ),
    ]
