# Generated by Django 3.2.4 on 2023-10-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_preguntas_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preguntas',
        ),
    ]
