# Generated by Django 4.2.5 on 2023-11-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
